openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
servers:
- url: https://roborest.ipgpromo.ru
x-yc-apigateway:
  cors:
    origin:
      - "http://localhost:3000"   
  service_account_id: aje6dehln13ntd0urarq
paths:
  /ui/{proxy+}:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: roborest-ui
        object: "/ui/{proxy}"
        default_object: "/ui/{proxy}/index.html"
    post:
      x-yc-apigateway-integration:
        type: dummy
        http_code: 302
        http_headers:
          Location: /ui/{proxy}
        content: 
          '*': redirect
    parameters:
      - name: proxy
        in: path
        required: true
        schema:
          type: string
  /eval:
    post:
      x-yc-apigateway-integration:
        payload_format_version: '1.0'
        function_id: d4en1jo3phaifglc2jp8
        tag: $latest
        type: cloud_functions
  /options:
    post:
      x-yc-apigateway-integration:
        payload_format_version: '1.0'
        function_id: d4eckgg16mfr6oo9n0c8
        tag: $latest
        type: cloud_functions
  /get-activity:
    post:
      x-yc-apigateway-integration:
        payload_format_version: '1.0'
        function_id: d4ejslurbm1rm9c8ctj9
        tag: $latest
        type: cloud_functions
  /set-activity:
    post:
      x-yc-apigateway-integration:
        payload_format_version: '1.0'
        function_id: d4e41m97e79he17428s5
        tag: $latest
        type: cloud_functions
  /install:
    post:
      x-yc-apigateway-integration:
        payload_format_version: '1.0'
        function_id: d4eh41tf5cmpb54ia871
        tag: $latest
        type: cloud_functions
