openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
servers:
- url: https://d5dfibnvjutmk39e6uao.yl4tuxdu.apigw.yandexcloud.net
x-yc-apigateway:
  cors:
    origin:
      - "http://localhost:3000"   
  service_account_id: aje6dehln13ntd0urarq
paths:
  /ui/{proxy+}:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: roborest-ui
        object: "/ui/{proxy}"
        default_object: "/ui/{proxy}/index.html"
    post:
      x-yc-apigateway-integration:
        type: dummy
        http_code: 302
        http_headers:
          Location: /ui/{proxy}
        content: 
          '*': redirect
    parameters:
      - name: proxy
        in: path
        required: true
        schema:
          type: string
  /eval:
    post:
      x-yc-apigateway-integration:
        payload_format_version: '1.0'
        function_id: d4en1jo3phaifglc2jp8
        tag: $latest
        type: cloud_functions
