name: Function refresh

on:
  push:
    branches:
      - main
    paths:
      - "functions/refresh/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy Function
        id: sls-func
        uses: yc-actions/yc-sls-function@v4
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          yc-sa-id: 'aje6dehln13ntd0urarq'
          folder-id: 'b1gcfvr4j5v19q1pbtav'
          function-name: 'refresh'
          runtime: 'python312'
          memory: '256Mb'
          entrypoint: 'index.handler'
          working-directory: functions/refresh
          include: |
            ../libs/*
            index.py  
            requirements.txt

