name: Deploy API Gateway

on:
  push:
    branches:
      - main
    paths:
      - "function/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy Function
        id: sls-func
        uses: yc-actions/yc-sls-function@v4
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          bucket: ${{ secrets.BUCKET }}
          folder-id: 'b1g*********'
          function-name: 'test-function'
          runtime: 'nodejs16'
          memory: '256Mb'
          entrypoint: 'src/main.handler'
          environment: |
            DEBUG=True
            COUNT=1
          include: |
            ./src
            package.json
          exclude: |
            **/*.ts
          tags: |
            ${{ GITHUB_SHA::6 }}
            foo
          secrets: |
            DB_PASSWORD=lockbox-secret-id/latest/password
            API_KEY=lockbox-secret-id/abcdef123456/api_key