name: Deploy to Yandex Cloud S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build Nuxt 3
        run: npm run build

      - name: Export static files
        run: npm run generate

      - name: Sync to Yandex S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete --exact-timestamps
        env:
          AWS_S3_BUCKET: roborest-ui
          AWS_ACCESS_KEY_ID: ${{ secrets.YC_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET }}
          AWS_REGION: ru-central1
          SOURCE_DIR: .output/public
          DEST_DIR: ui
          ENDPOINT_URL: https://storage.yandexcloud.net
